### ISSUE TITLE
How do you predict SOM for a new molecule?

### ISSUE THREAD

**Issue by sistar2020** [molinfo-vienna/FAME.AL#2]
It'll be helpful if some examples are provided for predicting SOM of a new molecule.

**Comment by anya-chen** [comment]
> It'll be helpful if some examples are provided for predicting SOM of a new molecule.

Thank you for your interest. This repository demonstrates an active learning workflow for SoM data measurement and annotation. However, it does not include a standalone SoM predictor. If you're looking to predict SoMs for molecules, please check out our FAME 3 tool here:  https://nerdd.univie.ac.at/fame3/.
